# Generated by Django 3.2 on 2022-05-22 05:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20220522_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('6f22181c-4a78-4a23-82c6-a118acc4027b')),
        ),
    ]
