# Generated by Django 3.2 on 2022-05-23 19:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('978bf03b-751a-4944-936e-78ffb3ee0c27')),
        ),
    ]
