# Generated by Django 3.2 on 2022-05-23 20:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20220523_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('b425a19d-c9fd-4511-ab7c-ed47b40b2b45')),
        ),
    ]
