# Generated by Django 3.2 on 2022-05-24 00:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20220523_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('e4bd8490-88dd-4d2c-9b17-4900c957295e')),
        ),
    ]
