# Generated by Django 3.2 on 2022-05-24 00:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('ce96b53c-7673-49fd-87e7-152b7dd204a7')),
        ),
    ]
