# Generated by Django 3.2 on 2022-05-24 00:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_alter_book_book_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='owner',
        ),
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('44de2ca0-414a-4a24-8e69-d9d5e97488cf')),
        ),
    ]
