# Generated by Django 3.2 on 2022-05-24 02:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_auto_20220524_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('e05d7d18-9019-4d2c-8e85-d56a88f3fe88')),
        ),
    ]
