# Generated by Django 3.2 on 2022-05-24 03:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_auto_20220524_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('91d9dfde-8823-4ab7-a5f5-66e0e4de628f')),
        ),
    ]
