# Generated by Django 3.2 on 2022-05-24 03:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_alter_book_book_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='des',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('c9765ec7-28aa-497d-87c7-715829d7ea32')),
        ),
    ]
