# Generated by Django 3.2 on 2022-05-25 00:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_auto_20220524_0334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publication_date',
            new_name='date_of_publication',
        ),
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('fdb4577b-b411-424e-8a04-73ebeac8f31e')),
        ),
    ]
