# Generated by Django 3.2 on 2022-05-26 15:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_auto_20220525_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('6bd1d741-5cb5-4d23-8ef2-8d1d3b36a7ee')),
        ),
    ]
