# Generated by Django 3.2 on 2022-05-26 17:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_alter_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('9e0a86dd-4d5f-4a11-8e9a-592b6c1cb09c')),
        ),
    ]
