# Generated by Django 3.2 on 2022-05-27 00:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_alter_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('b8b2c4cf-d23c-4da9-9815-779de5a66cbd')),
        ),
    ]
