# Generated by Django 3.2 on 2022-05-27 00:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_alter_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('f917770f-0514-46e0-98f3-f6e11a73808e')),
        ),
    ]
