# Generated by Django 3.2 on 2022-05-27 00:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0019_alter_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('12a03d2c-7122-4e8e-ae5a-ae8159cad40e')),
        ),
    ]
