# Generated by Django 3.2 on 2022-05-22 05:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookcase', '0002_auto_20220522_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='rack_id',
            field=models.UUIDField(default=uuid.UUID('5a39e85e-cf1c-46c4-a5c3-a18664542be1')),
        ),
    ]
