# Generated by Django 3.2 on 2022-05-23 19:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookcase', '0003_alter_rack_rack_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='rack_id',
            field=models.UUIDField(default=uuid.UUID('7ae9bd0a-be87-4341-a4c7-cd20a43e276b')),
        ),
    ]
