# Generated by Django 3.2 on 2022-05-23 20:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookcase', '0004_alter_rack_rack_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='rack_id',
            field=models.UUIDField(default=uuid.UUID('ee8be833-ea17-4959-84d4-27bcc0bf2610')),
        ),
    ]
