# Generated by Django 3.2 on 2022-05-23 20:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookcase', '0005_alter_rack_rack_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookitem',
            name='owner',
        ),
        migrations.AlterField(
            model_name='rack',
            name='rack_id',
            field=models.UUIDField(default=uuid.UUID('5e9df2a9-c033-469c-89d4-f531ab351498')),
        ),
    ]
