# Generated by Django 3.2 on 2022-05-23 21:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookcase', '0007_alter_rack_rack_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='rack_id',
            field=models.UUIDField(default=uuid.UUID('fb3ed4af-c7ca-49bb-bd89-361c2efd3fc2')),
        ),
    ]
