# Generated by Django 3.2 on 2022-05-24 00:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookcase', '0008_alter_rack_rack_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='rack_id',
            field=models.UUIDField(default=uuid.UUID('4a8f2680-a34c-497b-8765-f21d1fb2f552')),
        ),
    ]
