# Generated by Django 3.2 on 2022-05-24 00:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookcase', '0009_alter_rack_rack_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='rack_id',
            field=models.UUIDField(default=uuid.UUID('b0043a53-4541-4645-8c61-b72972e25852')),
        ),
    ]
