# Generated by Django 3.2 on 2022-05-24 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookcase', '0010_alter_rack_rack_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookitem',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rack',
            name='rack_id',
            field=models.UUIDField(default=uuid.UUID('682c9e48-33d5-4cb2-a9bb-e687695c71a1')),
        ),
    ]
