# Generated by Django 3.2 on 2022-05-24 03:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookcase', '0012_alter_rack_rack_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='rack_id',
            field=models.UUIDField(default=uuid.UUID('87d170d6-24fb-4583-b752-6c9b01b49305')),
        ),
    ]
