# Generated by Django 3.2 on 2022-05-24 03:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookcase', '0013_alter_rack_rack_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='rack_id',
            field=models.UUIDField(default=uuid.UUID('9fc9d0c6-82a1-493f-9617-5e7e5cd10a05')),
        ),
    ]
