# Generated by Django 3.2 on 2022-05-25 00:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookcase', '0014_alter_rack_rack_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='rack_id',
            field=models.UUIDField(default=uuid.UUID('be6cbed8-941f-4517-b414-a88b00a6a1b8')),
        ),
    ]
