# Generated by Django 3.2 on 2022-05-26 15:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookcase', '0015_alter_rack_rack_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='rack_id',
            field=models.UUIDField(default=uuid.UUID('a28e577f-571f-4e77-8fc1-cf849e6fb587')),
        ),
    ]
