# Generated by Django 3.2 on 2022-05-26 17:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_alter_book_book_id'),
        ('bookcase', '0016_alter_rack_rack_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookitem',
            old_name='owner',
            new_name='current_owner',
        ),
        migrations.RemoveField(
            model_name='bookitem',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='rack',
            name='books',
        ),
        migrations.AlterField(
            model_name='bookitem',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.book'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='rack_id',
            field=models.UUIDField(default=uuid.UUID('8798fa2c-68b7-4434-bad4-e5dbed5bb2f0')),
        ),
    ]
