# Generated by Django 3.2 on 2022-05-27 00:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookcase', '0017_auto_20220526_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='rack_id',
            field=models.UUIDField(default=uuid.UUID('75121e90-99c3-400d-a7f4-405663a4dd66')),
        ),
    ]
