# Generated by Django 3.2 on 2022-05-27 00:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookcase', '0018_alter_rack_rack_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='rack_id',
            field=models.UUIDField(default=uuid.UUID('df96bfd1-f6e7-4407-a4e3-6fe7d18c48c3')),
        ),
    ]
