# Generated by Django 3.2 on 2022-05-27 00:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookcase', '0019_alter_rack_rack_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='rack_id',
            field=models.UUIDField(default=uuid.UUID('2d9d2abf-d21f-4532-ae61-5acd2e640641')),
        ),
    ]
